### ISSUE TITLE
Configuring the atecc

### ISSUE THREAD

**Issue by dogusural** [wirenboard/atecc-util#3]
Hey there,

Thank you for the great project. I have one question about the writing of the config. 

``` write-config input.bin|- ```

I have three questions regarding that command.

1. Why is there are |- sign at the end , why not just use the file name ?
2. Why is the config file is in _.bin_ format ?
3. Can you give a sample regarding the .bin file needed to configure the atecc608 ?

Thank you

**Comment by evgeny-boger** [comment]
> Why is there are |- sign at the end , why not just use the file name ?
`-` sign means read config from stdin. So it's either `write-config input.bin` or `write-config -`

> Why is the config file is in .bin format ?

Because it's the way the config is stored and written to device: binary format. The meaning of individual bits and bytes is described in ATECC608A/508A datasheet. 
You may use `dump-config` though which will show most of the config parameters in human-readable form alongside with binary format.

>Can you give a sample regarding the .bin file needed to configure the atecc608 ?

well, it's really not that easy. There are many many different use cases and writing config zone is one time operation (i.e. it can not be reversed). I would say you shoud use one supplied by Microchip in their appnotes and samples on AWS or Google IoT cloud service, for example.
